"""webclient -- declarative web client (ground-up rewrite in progress)."""

__version__ = "0.1.0"

from .clients import DEFAULT_WAIT, WaitConfig, WaitEvent
from .query.collection import Collection, Field
from .core.crawl import Crawl, Edge
from .core.client.models import Robots
from .core.document import Element, HtmlBacking, JsonBacking
from .policy import (
    AUTO,
    AntiBotPolicy,
    BrowserConfig,
    BrowserPolicy,
    ProxyPolicy,
    RatePolicy,
    Resolve,
    RetryPolicy,
)
from .core.web_core import Backing, WebCore
from . import log as _log  # noqa: F401  (installs the package NullHandler)
from .log import configure_logging, log_events
from .settings import LlmSettings, Settings, current as current_settings, use as use_settings
from .scripts import Script, ScriptPolicy, ScriptRegistry
from .trace import Trace, TraceReader
from .errors import (
    RAISE,
    RETURN,
    FetchError,
    RemoteError,
    RenderError,
    SelectError,
    WebError,
    WebException,
)
from .events import (
    ActionEvent,
    ConsoleEvent,
    DOMEvent,
    DOMUpdateEvent,
    ErrorEvent,
    Event,
    EventBus,
    EventRegistry,
    LoopEvent,
    NavigationEvent,
    NetworkEvent,
    PipelineEvent,
    PlanEvent,
    ResourceEvent,
    ScriptEvent,
    SnapshotEvent,
)
from .llm.agent import (
    AgentRun,
    Click,
    Done,
    Goto,
    Observation,
    Scroll,
    WaitFor,
    drive,
)
from .llm.guides import lazy_query_guide
from .query.expr import from_blob, from_describe, from_plan
from .interface import (
    AsyncDocument,
    AsyncReference,
    AsyncWebClient,
    Document,
    LiveDocument,
    Reference,
    RemoteWebClient,
    Session,
    WebClient,
    default_client,
    doc,
    field,
    filter,
    from_url,
    is_empty,
    is_ok,
    many,
    ref,
    reference,
    when,
    wq,
)

__all__ = [
    "WebClient",
    "AsyncWebClient",
    "AsyncReference",
    "AsyncDocument",
    "RemoteWebClient",
    "Session",
    "Document",
    "LiveDocument",
    "Reference",
    "Crawl",
    "Edge",
    "drive",
    "Observation",
    "AgentRun",
    "Click",
    "Done",
    "Goto",
    "Scroll",
    "WaitFor",
    "Element",
    "Robots",
    "Resolve",
    "RetryPolicy",
    "RatePolicy",
    "ProxyPolicy",
    "AntiBotPolicy",
    "BrowserConfig",
    "BrowserPolicy",
    "WaitConfig",
    "WaitEvent",
    "DEFAULT_WAIT",
    "AUTO",
    "Backing",
    "Settings",
    "LlmSettings",
    "current_settings",
    "use_settings",
    "configure_logging",
    "log_events",
    "Trace",
    "TraceReader",
    "Script",
    "ScriptPolicy",
    "ScriptRegistry",
    "__version__",
    "WebCore",
    "HtmlBacking",
    "JsonBacking",
    "from_url",
    "from_plan",
    "from_blob",
    "from_describe",
    "lazy_query_guide",
    "default_client",
    "Collection",
    "Field",
    "reference",
    "doc",
    "ref",
    "many",
    "wq",
    "field",
    "when",
    "filter",
    "is_empty",
    "is_ok",
    "RAISE",
    "RETURN",
    "WebError",
    "WebException",
    "RenderError",
    "SelectError",
    "FetchError",
    "RemoteError",
    "Event",
    "EventBus",
    "EventRegistry",
    "NetworkEvent",
    "NavigationEvent",
    "DOMEvent",
    "DOMUpdateEvent",
    "ActionEvent",
    "ConsoleEvent",
    "PlanEvent",
    "ErrorEvent",
    "LoopEvent",
    "PipelineEvent",
    "ScriptEvent",
    "SnapshotEvent",
    "ResourceEvent",
]
