"""webclient -- declarative web client (ground-up rewrite in progress)."""

from .clients import DEFAULT_WAIT, WaitConfig, WaitEvent
from .collection import Collection, Field
from .core.crawl import Crawl, Edge
from .core.client.models import Robots
from .core.document import Element, HtmlBacking, JsonBacking
from .core.reference.models import (
    AUTO,
    AntiBotPolicy,
    BrowserConfig,
    BrowserPolicy,
    ProxyPolicy,
    RatePolicy,
    Resolve,
    RetryPolicy,
)
from .core.web_core import Backing, WebCore
from .settings import LlmSettings, Settings
from .errors import (
    RAISE,
    RETURN,
    FetchError,
    RemoteError,
    RenderError,
    SelectError,
    WebError,
    WebException,
)
from .events import (
    ActionEvent,
    ConsoleEvent,
    DOMEvent,
    DOMUpdateEvent,
    Event,
    EventBus,
    EventRegistry,
    NavigationEvent,
    NetworkEvent,
    PlanEvent,
)
from .guides import lazy_query_guide
from .query.expr import from_blob, from_describe, from_plan
from .core.remote import RemoteWebClientCore
from .surfaces import (
    AsyncDocument,
    AsyncReference,
    AsyncWebClient,
    Document,
    LiveDocument,
    Reference,
    RemoteWebClient,
    Session,
    WebClient,
    default_client,
    doc,
    field,
    filter,
    from_url,
    is_empty,
    is_ok,
    many,
    ref,
    reference,
    when,
    wq,
)

__all__ = [
    "WebClient",
    "AsyncWebClient",
    "AsyncReference",
    "AsyncDocument",
    "RemoteWebClient",
    "RemoteWebClientCore",
    "Session",
    "Document",
    "LiveDocument",
    "Reference",
    "Crawl",
    "Edge",
    "Element",
    "Robots",
    "Resolve",
    "RetryPolicy",
    "RatePolicy",
    "ProxyPolicy",
    "AntiBotPolicy",
    "BrowserConfig",
    "BrowserPolicy",
    "WaitConfig",
    "WaitEvent",
    "DEFAULT_WAIT",
    "AUTO",
    "Backing",
    "Settings",
    "LlmSettings",
    "WebCore",
    "HtmlBacking",
    "JsonBacking",
    "from_url",
    "from_plan",
    "from_blob",
    "from_describe",
    "lazy_query_guide",
    "default_client",
    "Collection",
    "Field",
    "reference",
    "doc",
    "ref",
    "many",
    "wq",
    "field",
    "when",
    "filter",
    "is_empty",
    "is_ok",
    "RAISE",
    "RETURN",
    "WebError",
    "WebException",
    "RenderError",
    "SelectError",
    "FetchError",
    "RemoteError",
    "Event",
    "EventBus",
    "EventRegistry",
    "NetworkEvent",
    "NavigationEvent",
    "DOMEvent",
    "DOMUpdateEvent",
    "ActionEvent",
    "ConsoleEvent",
    "PlanEvent",
]
