"""The lazy typed tier -- static stubs for the recording surface.

At runtime every recording value is an ``Expr`` (see ``webclient.expr``); these
classes exist only for the type checker. A lazy op returns another lazy type;
``collect()`` (via the ``Lazy[T]`` bridge) and ``WebClient.execute`` materialise
it to the eager model. Generated/verified by ``scripts/gen_stubs.py`` from the
cores' fields + backing signatures.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Generic, Literal, TypeVar, overload

if TYPE_CHECKING:
    from .collection import Collection, Field
    from .surfaces import Document, Reference

T = TypeVar("T")
S = TypeVar("S")


class Lazy(Generic[T]):
    """Bridge: a recorded plan that materialises to ``T``."""

    def collect(self, context: Any = ...) -> T: ...


# >>> generated: lazy-tier <<<
class LazyField(Lazy["Field[S]"], Generic[S]):
    def get(self, default: Any = ...) -> S: ...
    def is_ok(self) -> "LazyField[bool]": ...
    def is_empty(self) -> "LazyField[bool]": ...
    def __eq__(self, other: Any) -> "LazyField[bool]": ...   # type: ignore[override]
    def __ne__(self, other: Any) -> "LazyField[bool]": ...   # type: ignore[override]
    def __and__(self, other: Any) -> "LazyField[bool]": ...
    def __or__(self, other: Any) -> "LazyField[bool]": ...
    def __invert__(self) -> "LazyField[bool]": ...
    def collect(self, context: Any = ...) -> "Field[S]": ...


class LazyReference(Lazy["Reference"]):
    url: "LazyField[str]"
    def resolve(self, *, browser: bool = ..., optional: bool = ...,
                error: Any = ...) -> "LazyDocument": ...
    def with_params(self, **params: str) -> "LazyReference": ...
    def replace(self, **fields: Any) -> "LazyReference": ...
    def join(self, href: str) -> "LazyReference": ...
    def collect(self, context: Any = ...) -> "Reference": ...


class LazyDocument(Lazy["Document"]):
    def select(self, selector: str, *, index: int = ...,
               error: Any = ...) -> "LazyDocument": ...
    def select_all(self, selector: str, *, limit: int | None = ...,
                   offset: int = ...) -> "LazyCollection[LazyDocument]": ...
    @overload
    def attr(self, name: Literal["href", "src", "action"]) -> "LazyReference": ...  # type: ignore[overload-overlap]
    @overload
    def attr(self, name: str, *, error: Any = ...) -> "LazyField[str]": ...
    def field(self, name: str) -> "LazyField[Any]": ...
    def reference(self, name: str) -> "LazyReference": ...
    def is_ok(self) -> "LazyField[bool]": ...
    def is_empty(self) -> "LazyField[bool]": ...
    def render(self, format: str, **options: Any) -> "LazyField[Any]": ...
    def collect(self, context: Any = ...) -> "Document": ...


class LazyCollection(Lazy["Collection[T]"], Generic[T]):
    def extract(self, **exprs: Any) -> "LazyCollection[T]": ...
    def filter(self, *predicates: Any) -> "LazyCollection[T]": ...
    def limit(self, n: int) -> "LazyCollection[T]": ...
    def documents(self, column: str) -> "LazyCollection[LazyDocument]": ...
    def project(self) -> "list[dict[str, Any]]": ...
    def collect(self, context: Any = ...) -> "Collection[T]": ...
# >>> end generated <<<


__all__ = ["Lazy", "LazyField", "LazyReference", "LazyDocument", "LazyCollection"]
