"""Concrete eager surfaces (hand-written for the MVP; to be generated by
``webclient.gen`` from the Cores' fields + backings)."""
from __future__ import annotations

from typing import Any

from .core.reference_core import HttpMethod, ReferenceCore
from .core.reference_core import from_url as _core_from_url
from .surface import Surface, surface


@surface(ReferenceCore)
class Reference(Surface):
    """A request spec (eager). ``url`` reads; ``with_params``/``replace``/
    ``join`` derive; ``resolve`` (later) fetches."""


def from_url(url: str, method: HttpMethod = "get",
             params: dict[str, str | list[str]] | None = None,
             headers: dict[str, str] | None = None,
             cookies: dict[str, str] | None = None) -> Reference:
    """Build a :class:`Reference` from a URL string."""
    return Reference(_core_from_url(url, method, params, headers, cookies))


__all__ = ["Reference", "from_url"]
