"""Concrete eager surfaces (hand-written for the MVP; to be generated by
``webclient.gen`` from the Cores' fields + backings)."""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel

from .core.client_core import WebClientCore
from .core.document_core import DocumentCore
from .core.reference_core import HttpMethod, ReferenceCore
from .core.reference_core import from_url as _core_from_url
from .surface import Surface, surface


@surface(ReferenceCore)
class Reference(Surface):
    """A request spec (eager): ``url``/``with_params``/``replace``/``join``/
    ``resolve``."""


@surface(DocumentCore)
class Document(Surface):
    """A resolved document (eager): ``select``/``select_all``/``attr``/``text``
    (render/live/events are later slices)."""


def from_url(url: str, method: HttpMethod = "get",
             params: dict[str, str | list[str]] | None = None,
             headers: dict[str, str] | None = None,
             cookies: dict[str, str] | None = None) -> Reference:
    """Build a :class:`Reference` from a URL string."""
    return Reference(_core_from_url(url, method, params, headers, cookies))


class Renderer:
    """A (kind, format) render override -- register with ``wc.use``. Subclass
    and set ``name``/``kind``/``formats`` and implement ``render``."""

    name: str = ""
    kind: str = "html"
    formats: list[str] = []

    def render(self, document: "Document", format: str, **options: Any) -> Any:
        raise NotImplementedError


class SearchEngine(BaseModel):
    """A configurable search backend: a URL template (``{q}`` = the query) and
    the selectors that pick each result's title and link out of the page."""

    url: str
    result: str = ".result"
    title: str = "a"
    link: str = "a"


class Session:
    """A logical identity (cookies/headers/ttl) spanning fetches. ``ref``
    returns a lazy reference bound to this session."""

    def __init__(self, core: Any) -> None:
        self._core = core

    def ref(self, url: str, method: HttpMethod = "get", **kw: Any) -> Any:
        from .expr import Expr
        from .plan import Plan
        spec = _core_from_url(url, method, **kw).model_dump()
        return Expr(Plan(root="Reference", source=spec), self._core)

    @property
    def status(self) -> str:
        return self._core.status

    @property
    def cookies(self) -> dict[str, str]:
        return self._core.cookies


class _ClientBase:
    """The shared plan-building surface. ``WebClient`` and ``AsyncWebClient``
    build the same lazy plans off the same ``WebClientCore``; they differ only
    in how ``execute`` runs (sync bridge vs awaited off-thread)."""

    _core: WebClientCore

    def __init__(self, core: WebClientCore | None = None, **policy: Any) -> None:
        self._core = core if core is not None else WebClientCore(**policy)

    @property
    def bus(self) -> Any:
        """The client's event bus (subscribe to network/dom/console topics)."""
        return self._core.bus

    def use(self, renderer: Renderer) -> Any:
        self._core.use(renderer)
        return self

    def ref(self, url: str, method: HttpMethod = "get", **kw: Any) -> Any:
        """A lazy client-bound reference: ``.ref(url).resolve()...`` (statically
        a ``Reference``; at runtime an Expr recording a plan)."""
        from .expr import Expr
        from .plan import Plan
        spec = _core_from_url(url, method, **kw).model_dump()
        return Expr(Plan(root="Reference", source=spec), self._core)

    #: the same bound reference root as ``ref``.
    lazy = ref

    def fetch(self, url: str, *, optional: bool = False, error: Any = None,
              **kw: Any) -> Any:
        """A lazy fetch: ``ref(url).resolve()``; run it to materialise."""
        return self.ref(url, **kw).resolve(optional=optional, error=error)

    def session(self, *, ttl: float | None = None,
                headers: dict[str, str] | None = None, **kw: Any) -> Session:
        """A new session bound to this client's engine."""
        from .core.session_core import WebSessionCore
        core = WebSessionCore(ttl=ttl, headers=headers or {}, **kw)
        core._client = self._core
        return Session(core)

    def search(self, query: str, *, engine: SearchEngine,
               limit: int = 10) -> Any:
        """A lazy search plan: resolve the engine's query URL, then extract a
        (title, url) row per result. Run it to get the hits."""
        from .expr import doc
        plan = self.ref(engine.url.format(q=query)).resolve().select_all(engine.result)
        if limit:
            plan = plan.limit(limit)
        return plan.extract(title=doc.select(engine.title).attr("text"),
                            url=doc.select(engine.link).attr("href")).project()

    def summary(self, url: str, **kw: Any) -> Any:
        """A lazy plan resolving ``url`` to a title + markdown digest."""
        return self.ref(url, **kw).resolve().summary()

    def document(self, name: str) -> Document:
        """Recover a materialised Document by name (same surface object)."""
        from .surface import wrap
        return wrap(self._core.document(name))

    def reference(self, name: str) -> Reference:
        """Recover a Reference by its (root) name (same surface object)."""
        from .surface import wrap
        return wrap(self._core.reference(name))


class WebClient(_ClientBase):
    """The synchronous client surface: build lazy plans, run them on the engine
    loop. Owns (or is handed) a ``WebClientCore``."""

    def execute(self, expr: Any, context: Any = None, *, stream: bool = False,
                **kw: Any) -> Any:
        """Run a recorded lazy plan on this client (bridges the engine loop).
        ``stream=True`` yields rows (MVP: materialised then iterated)."""
        from .executor import evaluate
        result = evaluate(expr, context, client=self._core)
        return iter(result) if stream and isinstance(result, list) else result

    def close(self) -> None:
        self._core.close()

    def __enter__(self) -> "WebClient":
        return self

    def __exit__(self, *exc: object) -> None:
        self._core.close()


class AsyncWebClient(_ClientBase):
    """The async client surface: the very same plans as ``WebClient``, awaited.
    Execution runs the (sync) evaluator off the caller's loop so ``await`` does
    not block it."""

    async def execute(self, expr: Any, context: Any = None, *,
                      stream: bool = False, **kw: Any) -> Any:
        import asyncio

        from .executor import evaluate
        result = await asyncio.to_thread(evaluate, expr, context, client=self._core)
        return iter(result) if stream and isinstance(result, list) else result

    async def aclose(self) -> None:
        import asyncio
        await asyncio.to_thread(self._core.close)

    async def __aenter__(self) -> "AsyncWebClient":
        return self

    async def __aexit__(self, *exc: object) -> None:
        await self.aclose()


__all__ = ["Reference", "Document", "Session", "SearchEngine", "WebClient",
           "AsyncWebClient", "from_url"]
