class WebCore:
    """
    Capabilities + Dispatch + Backing + Chose
    """

class WebClientCore(WebCore):
    """
    Core Fields + Utility to talk with other Cores

    -> Backings e.g. Fetch, Search, Crawl, Session, Document

    e.g. 
    def execute():
        ... # Runs async execute on loop

    async execute():
        ... # Default plan execution with lazy

    def remote_execute():
        ... # Runs asnyc remote_execute on loop

    async def remote_execute():
        ... # Runs /execute over a websocket connection
    # The remote simply just replaces async def execute() with a post request / request over a websocket to keep up with eager 

    This also manages a ClientPool, The ClientPool uses ClientFactories which Init Client classes (our current clients are messy and all over the place)
    """

class WebSessionCore(WebCore):
    """
    Core Fields + Utility to talk with other Cores
    - Can be a shallow mimic of WebClientCore
    -> Backings e.g. Fetch, Search, Crawl, Session, Document
    """

class DocumentCore(WebCore):
    """
    Core Fields + Utility to talk with other Cores

    -> Backings
    """

class ReferenceCore(WebCore):
    """
    Core fields + Utility to talk with other Cores

    -> Backings e.g. from_url, url property
    """


# Expr models - Keep it agnostic from Core/Document, its just a simple external tool as originally planned

class Expr(metaclass=ExprMeta):
    def __init__(self, parent: Expr | None, root: type, op: str, *args, **kwargs):
        self.parent = parent
        self.root = root
        self.op = op
        self.args = args
        self.kwargs = kwargs

    # The return types should be resolved for Expr validation -> The static type checker is tricked already but we should 
    # Validate the expressions
    # These functions require special attention / should use a well build lib to extract this information 
    # There are lots of type hints - Technically validation is not needed but is nice to have
    # Example edge cases, BaseModel getattr will fail and need to check root.model_fields
    # Properties need _call_return_type
    def __getattr__(self, *args, **kwargs): 
        return_type = _attr_return_type(_self=self.root, root=self.root, name=args[0])
        return Expr(self, return_type, "__getattr__", *args, **kwargs)

    # More edge cases here
    # Is a class.__init__ e.g. ref(...)
    # Is overloaded (need to find the sig that matches the call args for the correct return type)
    # Has no return type -> Any
    # Has self return type -> self
    # Uses generics (cam use a runtime hack)
    # class X:; obj: _self; kind = typing.get_type_hint(X, localns={"_self": _self})["x"]
    # Is a union of types -> we need the most common base type or Any
    # Is list/sequence
    # Ideally we have a lib for all these type validation stuff
    def __call__(self, *args, **kwargs):
        return_type = _call_return_type(_self=self.parent.root if self.parent else None, root=self.root, *args, **kwargs)
        return Expr(self, return_type, "__call__", *args, **kwargs)



# Lazy objects have the fields from DocumentCore + any features from the Backings
# These are exposed as empty stubs on the Lazy Classes s.t. accessing them turns them into a lazy expr
# e.g.
class LazyDocument:
    """
    Auto generated from DocumentCore fields + Backings properties + methods
        DocumentCore -> LazyDocument
        [py-types] -> Field[T]
        Iterable/Sequence -> Collection[T]
    """


# Eager objects have the fields from DocumentCore + any features from the Backings
# These are exposed as empty stubs on the Eager Classes s.t. accessing them turns them into a lazy expr with a .collect()
# hence the machinery is much the same as Lazy just with a auto collect
# e.g.
class Document:
    """
    Auto generated from DocumentCore fields + Backings properties + methods
        DocumentCore -> Document
        [py-types] -> T
        Iterable/Sequence -> Iterable[T]
    """

class AsyncDocument(Document):
    """
    Autogenerated with Document has a simple flag _async=True -> plans are executed async and need an await
    The whole core should be async, so the non-async versions will need to be executed on a loop when _async=False
    """

