"""The typed lazy surfaces + the ``wq`` builder namespace.

At runtime every node in a ``wq`` chain is an :class:`~web.dsl.expr.Expr` recording a plan; these
Protocols are a pure TYPING overlay the roots are ``cast`` to, so a chain is statically typed and --
most importantly -- each terminal returns a PRECISE type, not ``object``/``Any``: a reference/
document chain collects a :class:`~web.parse.Document`, a collection chain a ``list[JsonValue]``, a
field chain a ``JsonValue``. The comparison dunders return a ``LazyField`` so ``attr("text") != ""``
is a recordable predicate usable inside ``filter`` / ``when``. This mirrors the monolith's generated
lazy surfaces -- same DSL, hand-written compact for the packages layer.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, cast, runtime_checkable

from pydantic import JsonValue

from .expr import Expr
from .plan import Plan, Step
from .values import Collection, Field

if TYPE_CHECKING:
    from web.parse import Document
    from web.resolve import Resolver


@runtime_checkable
class LazyField(Protocol):
    """A recorded scalar-leaf chain (a value read). Collects to its value."""

    def number(self, default: object = None) -> "LazyField": ...
    def date(self, format: str | None = None, *, dayfirst: bool = False, default: object = None) -> "LazyField": ...
    def datetime(self, format: str | None = None, *, dayfirst: bool = False, default: object = None) -> "LazyField": ...
    def split(self, sep: str | None = None, maxsplit: int = -1, *, regex: bool = False,
              strip: bool = True, keep_empty: bool = False) -> "LazyCollection": ...
    def map(self, mapping: "dict[str, JsonValue]", default: object = None) -> "LazyField": ...
    def link(self, base: str | None = None) -> "LazyField": ...
    def is_ok(self) -> "LazyField": ...
    def is_empty(self) -> "LazyField": ...
    def collect(self, root: object = None, *, resolver: "Resolver | None" = None) -> JsonValue: ...
    async def acollect(self, root: object = None, *, resolver: "Resolver | None" = None) -> JsonValue: ...
    def to_blob(self) -> str: ...
    def describe(self) -> str: ...
    def __eq__(self, o: object) -> "LazyField": ...  # type: ignore[override]
    def __ne__(self, o: object) -> "LazyField": ...  # type: ignore[override]
    def __lt__(self, o: object) -> "LazyField": ...
    def __le__(self, o: object) -> "LazyField": ...
    def __gt__(self, o: object) -> "LazyField": ...
    def __ge__(self, o: object) -> "LazyField": ...
    def __and__(self, o: object) -> "LazyField": ...
    def __or__(self, o: object) -> "LazyField": ...
    def __invert__(self) -> "LazyField": ...


class LazyValues(Protocol):
    """A recorded scalar FAN-OUT chain (an element read applied across a collection). Collects to a
    ``list[JsonValue]`` -- one value per element (e.g. ``select_all('a').attr('href')``)."""

    def number(self, default: object = None) -> "LazyValues": ...
    def date(self, format: str | None = None, *, dayfirst: bool = False, default: object = None) -> "LazyValues": ...
    def collect(self, root: object = None, *, resolver: "Resolver | None" = None) -> "list[JsonValue]": ...
    async def acollect(self, root: object = None, *, resolver: "Resolver | None" = None) -> "list[JsonValue]": ...
    def to_blob(self) -> str: ...
    def describe(self) -> str: ...


class LazyCollection(Protocol):
    """A recorded set-of-results chain. Collects to the extracted ROWS (``list[dict[str,
    JsonValue]]``) -- the smart terminal projects them, so no explicit ``.project()`` is needed;
    a scalar read (``attr``/``text``/``links``) narrows to :class:`LazyValues`."""

    def select(self, css: str) -> "LazyCollection": ...
    def select_all(self, css: str) -> "LazyCollection": ...
    def attr(self, name: str) -> "LazyValues": ...
    def text(self) -> "LazyValues": ...
    def links(self) -> "LazyValues": ...
    def reference(self, name: str) -> "LazyReference": ...
    def field(self, name: str) -> "LazyField": ...
    def extract(self, **columns: "LazyField | LazyValues | LazyCollection | LazyDocument | LazyReference | JsonValue") -> "LazyCollection": ...
    def filter(self, *predicates: "LazyField | LazyValues | JsonValue") -> "LazyCollection": ...
    def limit(self, n: int) -> "LazyCollection": ...
    def distinct(self) -> "LazyCollection": ...
    def documents(self, column: str) -> "LazyCollection": ...
    def merge(self) -> "LazyField": ...
    def project(self, *, flatten: bool = False, sep: str = ".", distinct: bool = False) -> "LazyCollection": ...
    def collect(self, root: object = None, *, resolver: "Resolver | None" = None) -> "list[dict[str, JsonValue]]": ...
    async def acollect(self, root: object = None, *, resolver: "Resolver | None" = None) -> "list[dict[str, JsonValue]]": ...
    def to_blob(self) -> str: ...
    def describe(self) -> str: ...


class LazyDocument(Protocol):
    """A recorded single-document chain (a resolved page, or a nested ``select``). Collects to a
    :class:`~web.parse.Document`; reads narrow to a field/collection."""

    def doc(self) -> "LazyDocument": ...
    def select(self, selector: str) -> "LazyDocument": ...
    def select_all(self, selector: str) -> "LazyCollection": ...
    def attr(self, name: str) -> "LazyField": ...
    def text(self) -> "LazyField": ...
    def links(self) -> "LazyValues": ...
    def reference(self, name: str) -> "LazyReference": ...
    def field(self, name: str) -> "LazyField": ...
    def collect(self, root: object = None, *, resolver: "Resolver | None" = None) -> "Document": ...
    async def acollect(self, root: object = None, *, resolver: "Resolver | None" = None) -> "Document": ...
    def to_blob(self) -> str: ...
    def describe(self) -> str: ...


class LazyReference(Protocol):
    """A recorded reference chain (a request spec). ``resolve()`` fetches it into a document."""

    def resolve(self) -> "LazyDocument": ...
    def collect(self, root: object = None, *, resolver: "Resolver | None" = None) -> "Document": ...
    async def acollect(self, root: object = None, *, resolver: "Resolver | None" = None) -> "Document": ...
    def to_blob(self) -> str: ...
    def describe(self) -> str: ...


class _When:
    """The ``when(cond).then(a).otherwise(b)`` conditional builder -- records a single ``when`` step
    whose three parts are sub-expressions evaluated against the surrounding element."""

    __slots__ = ("_cond", "_then")

    def __init__(self, cond: object) -> None:
        self._cond = cond
        self._then: object = _MISSING

    def then(self, value: object) -> "_When":
        """The value taken when the condition is truthy; returns self so ``.otherwise`` chains."""
        self._then = value
        return self

    def otherwise(self, value: object) -> LazyField:
        """The else-value; finishes the branch and returns the recorded ``Expr`` (as a LazyField)."""
        if self._then is _MISSING:
            raise TypeError("when(...).then(...) before .otherwise(...)")
        from .expr import to_arg

        step = Step(kind="when", args=[to_arg(self._cond), to_arg(self._then), to_arg(value)])
        return cast(LazyField, Expr(Plan(steps=[step])))


_MISSING: object = object()
_DOC: LazyDocument = cast(LazyDocument, Expr(Plan(root="Document")))


class _Wq:
    """The ``wq`` namespace: lazy roots (``wq.doc`` / ``wq.ref``) and the free builders
    (``reference`` / ``when`` / ``field`` / ``filter`` / ``is_ok`` / ``is_empty``)."""

    doc: LazyDocument = _DOC
    ref: LazyReference = cast(LazyReference, Expr(Plan(root="Reference")))

    def reference(self, url: str) -> LazyReference:
        """A lazy reference root starting from ``url`` -- the clean entry (no hand-built Request)."""
        return cast(LazyReference, Expr(Plan(root="Reference", source=url)))

    def field(self, name: str) -> LazyField:
        """A value already extracted in the surrounding row."""
        return _DOC.field(name)

    def when(self, cond: object) -> _When:
        """Start a conditional: ``when(cond).then(a).otherwise(b)``."""
        return _When(cond)

    def filter(self, collection: LazyCollection,
               *predicates: "LazyField | LazyValues | JsonValue") -> LazyCollection:
        """Free-function form of the collection filter: ``filter(coll, pred)`` == ``coll.filter(pred)``."""
        return collection.filter(*predicates)

    def is_ok(self, expr: LazyField) -> LazyField:
        """Free-function form of ``x.is_ok()``."""
        return expr.is_ok()

    def is_empty(self, expr: LazyField) -> LazyField:
        """Free-function form of ``x.is_empty()``."""
        return expr.is_empty()


wq = _Wq()


__all__ = ["wq", "LazyReference", "LazyDocument", "LazyCollection", "LazyValues", "LazyField",
           "Collection", "Field"]
