"""Two-tier typing stubs (PLAN §8).

The *lazy* tier is what the surface exposes: every op returns another lazy
type, and ``collect()`` returns the *materialised* tier (the engine models --
``Document``/``Reference``/``Field``/``Collection``). At runtime every lazy
value is one generic ``Expr``; these Protocols exist only for the type checker
(``lazy(cls)`` casts an ``Expr`` to the matching lazy tier). Keeping the tier a
stub -- not a real class -- preserves the independent, generic recorder.

Hand-written for now; generating them from the model ops (like the
``Collection`` element block) is a follow-up.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, Protocol, overload

if TYPE_CHECKING:
    from ..core.base import Collection, Field
    from ..document import Document, Reference

_LINK = Literal["href", "src", "action"]
_E = Any                                      # error-policy arg (kept loose)


class LazyField[T](Protocol):
    """A lazy scalar; ``collect()`` -> ``Field[T]`` (then ``.get()`` -> T)."""
    def collect(self) -> "Field[T]": ...
    def get(self) -> T: ...
    def is_ok(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def is_empty(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def when(self, cond: "LazyField[bool] | bool") -> "LazyField[T]": ...
    def then(self, value: Any) -> "LazyField[T]": ...
    def otherwise(self, value: Any) -> "LazyField[T]": ...
    def __eq__(self, o: Any) -> "LazyField[bool]": ...       # type: ignore[override]
    def __ne__(self, o: Any) -> "LazyField[bool]": ...       # type: ignore[override]
    def __lt__(self, o: Any) -> "LazyField[bool]": ...
    def __le__(self, o: Any) -> "LazyField[bool]": ...
    def __gt__(self, o: Any) -> "LazyField[bool]": ...
    def __ge__(self, o: Any) -> "LazyField[bool]": ...
    def __and__(self, o: Any) -> "LazyField[bool]": ...
    def __or__(self, o: Any) -> "LazyField[bool]": ...
    def __invert__(self) -> "LazyField[bool]": ...


class LazyReference(Protocol):
    def resolve(self, *, browser: bool = ..., session: Any = ...,
                optional: bool = ..., error: _E = ..., **o: Any) -> "LazyDocument": ...
    def with_params(self, **params: str) -> "LazyReference": ...
    def replace(self, **fields: Any) -> "LazyReference": ...
    def join(self, href: str) -> "LazyReference": ...
    def collect(self) -> "Reference": ...


class LazyDocument(Protocol):
    def select(self, selector: str, *, index: int = ..., wait: Any = ...,
               error: _E = ...) -> "LazyDocument": ...
    def select_all(self, selector: str, limit: int | None = ..., offset: int = ...,
                   *, error: _E = ...) -> "LazyCollection": ...
    @overload
    def attr(self, name: _LINK, *, error: _E = ...) -> LazyReference: ...  # type: ignore[overload-overlap]
    @overload
    def attr(self, name: str, *, error: _E = ...) -> "LazyField[str]": ...
    def render(self, format: str = ..., **options: Any) -> Any: ...
    def extract(self, *, error: _E = ..., **named: Any) -> "LazyDocument": ...
    def project(self, model: Any = ..., *, error: _E = ...) -> Any: ...
    def field(self, name: str, *, error: _E = ...) -> "LazyField[Any]": ...
    def reference(self, name: str, *, error: _E = ...) -> LazyReference: ...
    def references(self, *names: str, error: _E = ...) -> "LazyCollection": ...
    def document(self, name: str, *, error: _E = ...) -> "LazyDocument": ...
    def documents(self, *names: str, error: _E = ...) -> "LazyCollection": ...
    def is_ok(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def is_empty(self, *, error: _E = ...) -> "LazyField[bool]": ...
    # live interactions (return the same live document, lazily)
    def click(self, selector: str | None = ..., **k: Any) -> "LazyDocument": ...
    def write(self, selector: str, text: str, **k: Any) -> "LazyDocument": ...
    def press(self, key: str, **k: Any) -> "LazyDocument": ...
    def hover(self, selector: str, **k: Any) -> "LazyDocument": ...
    def check(self, selector: str, checked: bool = ..., **k: Any) -> "LazyDocument": ...
    def select_option(self, selector: str, **k: Any) -> "LazyDocument": ...
    def upload(self, selector: str, files: Any, **k: Any) -> "LazyDocument": ...
    def drag(self, source: str, target: str, **k: Any) -> "LazyDocument": ...
    def scroll(self, selector: str | None = ..., **k: Any) -> "LazyDocument": ...
    def execute(self, script: str, **k: Any) -> "LazyDocument": ...
    def evaluate(self, script: str, **k: Any) -> "LazyField[Any]": ...
    def screenshot(self, selector: str | None = ..., **k: Any) -> "LazyDocument": ...
    def wait_for(self, selector: str | None = ..., **k: Any) -> "LazyDocument": ...
    def collect(self) -> "Document": ...


class LazyCollection(Protocol):
    def select(self, selector: str, *, index: int = ...) -> "LazyCollection": ...
    def select_all(self, selector: str, **k: Any) -> "LazyCollection": ...
    def attr(self, name: str, *, error: _E = ...) -> "LazyCollection": ...
    def extract(self, *, error: _E = ..., **named: Any) -> "LazyCollection": ...
    def filter(self, *expr: Any, error: _E = ..., **named: Any) -> "LazyCollection": ...
    def project(self, model: Any = ..., *, error: _E = ...) -> Any: ...
    def references(self, *names: str, error: _E = ...) -> "LazyCollection": ...
    def documents(self, *names: str, error: _E = ...) -> "LazyCollection": ...
    def is_ok(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def is_empty(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def collect(self) -> "Collection[Any]": ...


__all__ = ["LazyDocument", "LazyReference", "LazyCollection", "LazyField"]
