"""Two-tier typing stubs (PLAN §8), generated by ``scripts/gen_stubs.py``.

The *lazy* tier is what the surface exposes: every op returns another lazy
type, and ``collect()`` -- defined once on the generic ``Lazy[T]`` base --
returns the *materialised* tier (the engine models ``Document`` / ``Reference``
/ ``Field`` / ``Collection``). At runtime every lazy value is one generic
``Expr``; these Protocols exist only for the type checker (``lazy(cls)`` / the
client facade cast an ``Expr`` to the matching lazy tier). Keeping the tier a
stub -- not a real class -- preserves the independent, generic recorder.

``Lazy[T]`` is the bridge the client uses for ``execute``: a lazy input of any
tier maps to its materialised ``T`` (``wc.execute(wc.fetch(u)) -> Document``).

The class bodies below the marker are GENERATED from the model ops so they
cannot drift -- edit the ops (or the generator), never this block:

    python scripts/gen_stubs.py          # rewrite
    python scripts/gen_stubs.py --check  # CI / test_typing
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, Protocol, overload

if TYPE_CHECKING:
    from collections.abc import Sequence  # noqa: F401  (used by generated sigs)


class WebError(BaseModel):
    """A serializable failure carried by a WebBase -- never a bare Exception
    on the wire."""

    type: str
    message: str
    detail: dict[str, Any] = {}

    @classmethod
    def from_exception(cls, exc: BaseException) -> WebError:
        return cls(type=type(exc).__name__, message=str(exc))


class WebBase(BaseModel):
    """Addressable, error-carrying base of every surface object. Names/roots
    are assigned by the resolver that registers the object (Decision 9)."""

    name: str = ""                  # short, low-entropy: doc:000-001
    kind: str = ""
    root: str | None = None         # name of the object this derives from
    created: int = 0
    updated: int = 0
    accessed: int = 0
    error: WebError | None = None
    message: str | None = None
    ok: bool = True                 # the ONLY truth; `error` is diagnostics

    _registrable: ClassVar[bool] = True
    _client: Any = PrivateAttr(default=None)        # owning WebClient
    _session: Any = PrivateAttr(default=None)
    _fields: dict[str, Any] = PrivateAttr(default_factory=dict)

    if not TYPE_CHECKING:
        def __getattr__(self, name: str) -> Any:
            """Ops live in ``core.ops``, not on this data class (PLAN §9): a
            bare eager call (e.g. on a collected Document) is dispatched to the
            registry. ``_``-names and model fields are pydantic's; an
            unregistered name raises as usual."""
            if name.startswith("_"):
                return super().__getattr__(name)
            from .ops import CALL_OPS, PROP_OPS, _lookup, read_prop, run_op
            if _lookup(PROP_OPS, self, name) is not None:
                return read_prop(self, name)
            if _lookup(CALL_OPS, self, name) is not None:
                return lambda *a, **k: run_op(self, name, list(a), k)
            return super().__getattr__(name)

    # -- extraction / accessors ----------------------------------------------
    # Every op (extract/project/field/reference(s)/document(s)/is_ok/is_empty)
    # lives in ``core.ops`` (PLAN §9); WebBase is data + the ``__getattr__``
    # dispatch above. Typed eager signatures are generated into the block below.
    if TYPE_CHECKING:
        # >>> eager:WebBase generated by scripts/gen_stubs.py -- do not edit
        def document(self, name: str, *, error: ErrorPolicy | None = None) -> Document: ...  # type: ignore[empty-body]
        def documents(self, *names: str, error: ErrorPolicy | None = None) -> Collection[Document]: ...  # type: ignore[empty-body]
        def extract(self, *, error: ErrorPolicy | None = None, **named_expr: Any) -> Self: ...  # type: ignore[empty-body]
        def field(self, name: str, *, error: ErrorPolicy | None = None) -> Field[Any]: ...  # type: ignore[empty-body]
        def is_empty(self, *, error: ErrorPolicy | None = None) -> Field[bool]: ...  # type: ignore[empty-body]
        def is_ok(self, *, error: ErrorPolicy | None = None) -> Field[bool]: ...  # type: ignore[empty-body]
        def project(self, model: Any = None, *, error: ErrorPolicy | None = None) -> Any: ...  # type: ignore[empty-body]
        def reference(self, name: str, *, error: ErrorPolicy | None = None) -> Reference: ...  # type: ignore[empty-body]
        def references(self, *names: str, error: ErrorPolicy | None = None) -> Collection[Reference]: ...  # type: ignore[empty-body]
        # <<< eager:WebBase
        pass


class Field[T](WebBase):
    """A scalar produced by a method. Comparisons and ``& | ~`` return a
    ``Field[bool]`` (so they work eagerly and, on a lazy ``Expr``, record).
    Never registered by name (Decision 3)."""

    value: Any = None

    _registrable: ClassVar[bool] = False

    def get(self) -> T:
        if not self.ok:
            raise OpError(self.error)
        return cast(T, self.value)

    def _cmp(self, name: str, other: object) -> Field[bool]:
        mine = self.get()
        theirs = other.get() if isinstance(other, Field) else other
        table: dict[str, Any] = {
            "eq": mine == theirs, "ne": mine != theirs,
            "lt": mine < theirs, "le": mine <= theirs,      # type: ignore[operator]
            "gt": mine > theirs, "ge": mine >= theirs,      # type: ignore[operator]
            "and": bool(mine) and bool(theirs),
            "or": bool(mine) or bool(theirs), "not": not mine}
        return Field[bool](value=table[name])

    def __eq__(self, o: object) -> Field[bool]: return self._cmp("eq", o)  # type: ignore[override]
    def __ne__(self, o: object) -> Field[bool]: return self._cmp("ne", o)  # type: ignore[override]
    def __lt__(self, o: object) -> Field[bool]: return self._cmp("lt", o)
    def __le__(self, o: object) -> Field[bool]: return self._cmp("le", o)
    def __gt__(self, o: object) -> Field[bool]: return self._cmp("gt", o)
    def __ge__(self, o: object) -> Field[bool]: return self._cmp("ge", o)
    def __and__(self, o: object) -> Field[bool]: return self._cmp("and", o)
    def __or__(self, o: object) -> Field[bool]: return self._cmp("or", o)
    def __invert__(self) -> Field[bool]: return self._cmp("not", None)

    __hash__ = None  # type: ignore[assignment]

    def __bool__(self) -> bool:
        return bool(self.get())


class Reference(WebBase):
    """A request spec plus the action chain and resolve options that led to a
    document (Decision 11): everything needed to (re)resolve it.

    Pure data (PLAN §9): ``Reference(hostname=...)`` builds one; the free
    ``reference(url)`` (core.expr) is the lazy root; construction/derivation
    helpers (``from_url``/``request_fields``/``bind``) are module functions and
    the ops (resolve/with_params/replace/join/url) live in core.ops."""

    kind: str = "webpage"
    hostname: str
    method: HttpMethod = "get"
    scheme: str = "https"
    port: int | None = None          # None -> default port for scheme
    path: str = ""
    fragment: str = ""

    params: dict[str, str | list[str]] = {}
    headers: dict[str, str] = {}
    cookies: dict[str, str] = {}
    body: bytes | None = None
    json_body: Any | None = None
    form: dict[str, str] | None = None
    follow_redirects: bool = True
    timeout: float | None = None
    actions: list[dict[str, Any]] = []   # ordered ops taken from the document
    options: dict[str, Any] = {}         # resolve options used (browser, ...)

    # Data only (PLAN §9): construction/derivation are module functions below
    # (``from_url`` / ``request_fields`` / ``bind``); ``url`` is a dispatched
    # prop; the ops (resolve/with_params/replace/join) live in core.ops. A lazy
    # reference root is the free ``reference(url)`` (core.expr).
    if TYPE_CHECKING:
        # >>> eager:Reference generated by scripts/gen_stubs.py -- do not edit
        def join(self, href: str) -> Reference: ...  # type: ignore[empty-body]
        def replace(self, **fields: Any) -> Reference: ...  # type: ignore[empty-body]
        def resolve(self, *, browser: bool = False, session: Any = None, optional: bool = False, error: ErrorPolicy | None = None, **options: Any) -> Document: ...  # type: ignore[empty-body]
        def with_params(self, **params: str) -> Reference: ...  # type: ignore[empty-body]
        @property
        def url(self) -> str: ...  # type: ignore[empty-body]
        # <<< eager:Reference
        pass


class Document(WebBase):
    """A resolved resource -- or an element of one (``select`` returns
    Documents whose backing is a subtree, root = the parent). A sibling of
    Reference (spec.py): it holds the *response* and its own action chain,
    and ``ref()`` returns the Reference it resolves from."""

    id: str = ""
    session_id: str | None = None
    kind: Literal["html", "json", "xml", "binary"] = "html"
    url: str = ""                    # the resolved (request) URL
    final_url: str | None = None     # after redirects
    content: bytes = b""
    status_code: int = 0
    response_headers: dict[str, str] = {}
    encoding: str | None = None
    elapsed: float | None = None
    events: list[Event] = []
    actions: list[dict[str, Any]] = []   # ordered ops taken from this document
    options: dict[str, Any] = {}         # resolve options used

    #: the DocumentCore (runtime/op machinery) is created lazily and cached
    #: here by ``core.ops.core_of``; Document itself is data (PLAN §9).
    _core_obj: Any = PrivateAttr(default=None)

    # Every op -- selection/actions/rendering, text/ref/join/reload, the event
    # views -- lives in core.ops and runs on the DocumentCore / backings.
    # Document is data + the generated eager interface below.

    if TYPE_CHECKING:
        # >>> eager:Document generated by scripts/gen_stubs.py -- do not edit
        @overload  # type: ignore[overload-overlap]
        def attr(self, name: Literal['href', 'src', 'action'], *, error: ErrorPolicy | None = None) -> Reference: ...
        @overload
        def attr(self, name: str, *, error: ErrorPolicy | None = None) -> Field[str]: ...
        def attr(self, name: str, *, error: ErrorPolicy | None = None) -> Any: ...  # type: ignore[empty-body]
        def check(self, selector: str, checked: bool = True, *, error: ErrorPolicy | None = None, **kw: Any) -> Document: ...  # type: ignore[empty-body]
        def click(self, selector: str | None = None, *, error: ErrorPolicy | None = None, **kw: Any) -> Document: ...  # type: ignore[empty-body]
        def drag(self, source: str, target: str, *, error: ErrorPolicy | None = None) -> Document: ...  # type: ignore[empty-body]
        def evaluate(self, script: str, *, error: ErrorPolicy | None = None) -> Any: ...  # type: ignore[empty-body]
        def events_of(self, event: 'type[Event] | Topic') -> Sequence[Event]: ...  # type: ignore[empty-body]
        def execute(self, script: str, *, error: ErrorPolicy | None = None) -> Document: ...  # type: ignore[empty-body]
        def hover(self, selector: str, *, error: ErrorPolicy | None = None, **kw: Any) -> Document: ...  # type: ignore[empty-body]
        def join(self, href: str) -> Reference: ...  # type: ignore[empty-body]
        def press(self, key: str, *, error: ErrorPolicy | None = None, **kw: Any) -> Document: ...  # type: ignore[empty-body]
        def ref(self) -> Reference: ...  # type: ignore[empty-body]
        def reload(self, **options: Any) -> Document: ...  # type: ignore[empty-body]
        @overload
        def render(self, format: Literal['markdown', 'text', 'html'], **options: Any) -> str: ...
        @overload
        def render(self, format: Literal['elements'], **options: Any) -> list[Element]: ...
        @overload
        def render(self, format: Literal['links'], **options: Any) -> Collection[Reference]: ...
        @overload
        def render(self, format: str, **options: Any) -> Any: ...
        def render(self, format: str, **options: Any) -> Any: ...  # type: ignore[empty-body]
        def screenshot(self, selector: str | None = None, *, error: ErrorPolicy | None = None, **kw: Any) -> Document: ...  # type: ignore[empty-body]
        def scroll(self, selector: str | None = None, *, x: int = 0, y: int = 0, error: ErrorPolicy | None = None) -> Document: ...  # type: ignore[empty-body]
        def select(self, selector: str, *, index: int = 0, wait: float | None = None, error: ErrorPolicy | None = None, optional: bool = False) -> Document: ...  # type: ignore[empty-body]
        def select_all(self, selector: str, limit: int | None = None, offset: int = 0, *, error: ErrorPolicy | None = None) -> Collection[Document]: ...  # type: ignore[empty-body]
        def select_option(self, selector: str, *, error: ErrorPolicy | None = None, **kw: Any) -> Document: ...  # type: ignore[empty-body]
        def subscribe(self, topic: 'Topic', handler: Any) -> Any: ...  # type: ignore[empty-body]
        def upload(self, selector: str, files: Sequence[str], *, error: ErrorPolicy | None = None) -> Document: ...  # type: ignore[empty-body]
        def wait_for(self, selector: str | None = None, *, error: ErrorPolicy | None = None, **kw: Any) -> Document: ...  # type: ignore[empty-body]
        def write(self, selector: str, text: str, *, error: ErrorPolicy | None = None, **kw: Any) -> Document: ...  # type: ignore[empty-body]
        @property
        def action_events(self) -> 'Sequence[ActionEvent]': ...  # type: ignore[empty-body]
        @property
        def console(self) -> 'Sequence[ConsoleEvent]': ...  # type: ignore[empty-body]
        @property
        def dom_mutations(self) -> 'Sequence[DOMUpdateEvent]': ...  # type: ignore[empty-body]
        @property
        def identity_path(self) -> str | None: ...  # type: ignore[empty-body]
        @property
        def text(self) -> str: ...  # type: ignore[empty-body]
        @property
        def title(self) -> str | None: ...  # type: ignore[empty-body]
        @property
        def xhr_requests(self) -> 'Sequence[XHREvent]': ...  # type: ignore[empty-body]
        # <<< eager:Document
        pass


class Collection[T](WebBase):
    """One address for many elements (Decision 10). Element ops (``select``,
    ``attr``, ``resolve``, ...) map over the elements; the whole-collection
    ops are ``_WHOLE``. Iteration is eager-only."""

    _items: list[Any] = PrivateAttr(default_factory=list)
    #: ops that act on the collection itself; everything else maps per element
    _WHOLE: ClassVar[frozenset[str]] = frozenset(
        {"extract", "filter", "project", "is_ok", "is_empty"})

    # The ops (extract/filter/project/is_ok/is_empty + the lifted element ops)
    # all live in core.ops (PLAN §9); Collection is data + iteration + the
    # ``__getattr__`` eager-lift below.
    def __iter__(self) -> Iterator[T]:
        return iter(self._items)

    def __len__(self) -> int:
        return len(self._items)

    if not TYPE_CHECKING:
        def __getattr__(self, name: str) -> Any:
            """Eager element-op lifting: an op not defined on Collection maps
            over the elements (the evaluator does the same in a plan).
            Flattens when an element op returns a Collection."""
            if name.startswith("_"):
                return super().__getattr__(name)   # pydantic private attrs
            from .ops import run_op
            if name in type(self)._WHOLE:           # acts on the collection itself
                return lambda *a, **k: run_op(self, name, list(a), k)

            def lifted(*args: Any, **kwargs: Any) -> Any:
                items: list[Any] = []
                for el in self._items:
                    r = run_op(el, name, list(args), kwargs)
                    items.extend(r) if isinstance(r, Collection) else items.append(r)
                if items and not all(isinstance(x, WebBase) for x in items):
                    return items          # plain values (e.g. projected dicts)
                out: Collection[Any] = Collection(root=self.name or None)
                out._items = items
                out._client, out._session = self._client, self._session
                return out
            return lifted

    if TYPE_CHECKING:
        # >>> generated by scripts/gen_stubs.py -- do not edit
        @overload  # type: ignore[overload-overlap]
        def attr(self, name: Literal['href', 'src', 'action'], *, error: ErrorPolicy | None = None) -> Collection[Reference]: ...
        @overload
        def attr(self, name: str, *, error: ErrorPolicy | None = None) -> Collection[Field[str]]: ...
        def attr(self, name: str, *, error: ErrorPolicy | None = None) -> Any: ...  # type: ignore[empty-body]
        def check(self, selector: str, checked: bool = True, *, error: ErrorPolicy | None = None, **kw: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def click(self, selector: str | None = None, *, error: ErrorPolicy | None = None, **kw: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def document(self, name: str, *, error: ErrorPolicy | None = None) -> Collection[Document]: ...  # type: ignore[empty-body]
        def documents(self, *names: str, error: ErrorPolicy | None = None) -> Collection[Document]: ...  # type: ignore[empty-body]
        def drag(self, source: str, target: str, *, error: ErrorPolicy | None = None) -> Collection[Document]: ...  # type: ignore[empty-body]
        def evaluate(self, script: str, *, error: ErrorPolicy | None = None) -> Collection[Any]: ...  # type: ignore[empty-body]
        def events_of(self, event: 'type[Event] | Topic') -> Collection[Sequence[Event]]: ...  # type: ignore[empty-body]
        def execute(self, script: str, *, error: ErrorPolicy | None = None) -> Collection[Document]: ...  # type: ignore[empty-body]
        def field(self, name: str, *, error: ErrorPolicy | None = None) -> Collection[Field[Any]]: ...  # type: ignore[empty-body]
        def hover(self, selector: str, *, error: ErrorPolicy | None = None, **kw: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def join(self, href: str) -> Collection[Reference]: ...  # type: ignore[empty-body]
        def press(self, key: str, *, error: ErrorPolicy | None = None, **kw: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def ref(self) -> Collection[Reference]: ...  # type: ignore[empty-body]
        def reference(self, name: str, *, error: ErrorPolicy | None = None) -> Collection[Reference]: ...  # type: ignore[empty-body]
        def references(self, *names: str, error: ErrorPolicy | None = None) -> Collection[Reference]: ...  # type: ignore[empty-body]
        def reload(self, **options: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def render(self, format: str, **options: Any) -> Collection[Any]: ...  # type: ignore[empty-body]
        def replace(self, **fields: Any) -> Collection[Reference]: ...  # type: ignore[empty-body]
        def resolve(self, *, browser: bool = False, session: Any = None, optional: bool = False, error: ErrorPolicy | None = None, **options: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def screenshot(self, selector: str | None = None, *, error: ErrorPolicy | None = None, **kw: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def scroll(self, selector: str | None = None, *, x: int = 0, y: int = 0, error: ErrorPolicy | None = None) -> Collection[Document]: ...  # type: ignore[empty-body]
        def select(self, selector: str, *, index: int = 0, wait: float | None = None, error: ErrorPolicy | None = None, optional: bool = False) -> Collection[Document]: ...  # type: ignore[empty-body]
        def select_all(self, selector: str, limit: int | None = None, offset: int = 0, *, error: ErrorPolicy | None = None) -> Collection[Document]: ...  # type: ignore[empty-body]
        def select_option(self, selector: str, *, error: ErrorPolicy | None = None, **kw: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def subscribe(self, topic: 'Topic', handler: Any) -> Collection[Any]: ...  # type: ignore[empty-body]
        def upload(self, selector: str, files: Sequence[str], *, error: ErrorPolicy | None = None) -> Collection[Document]: ...  # type: ignore[empty-body]
        def wait_for(self, selector: str | None = None, *, error: ErrorPolicy | None = None, **kw: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def with_params(self, **params: str) -> Collection[Reference]: ...  # type: ignore[empty-body]
        def write(self, selector: str, text: str, *, error: ErrorPolicy | None = None, **kw: Any) -> Collection[Document]: ...  # type: ignore[empty-body]
        def extract(self, *, error: ErrorPolicy | None = None, **named_expr: Any) -> Collection[T]: ...  # type: ignore[empty-body]
        def filter(self, *expr: Any, error: ErrorPolicy | None = None, **named_expr: Any) -> Collection[T]: ...  # type: ignore[empty-body]
        def project[M](self, model: type[M] | None = None, *, error: ErrorPolicy | None = None) -> list[M | dict[str, Any]]: ...  # type: ignore[empty-body]
        def is_ok(self, *, error: ErrorPolicy | None = None) -> Field[bool]: ...  # type: ignore[empty-body]
        def is_empty(self, *, error: ErrorPolicy | None = None) -> Field[bool]: ...  # type: ignore[empty-body]
        # <<< generated
        pass


_LINK = Literal["href", "src", "action"]
_E = Any                                      # error-policy arg (kept loose)


class Lazy[T](Protocol):
    """What every lazy tier has in common: ``collect()`` (and, via the client,
    ``execute``) evaluates the recorded plan into the materialised model
    ``T``."""
    def collect(self) -> T: ...


# >>> generated by scripts/gen_stubs.py -- do not edit
class LazyField[T](Lazy["Field[T]"], Protocol):
    """A lazy scalar; ``collect()`` -> ``Field[T]`` (then ``.get()`` -> T)."""
    def get(self) -> T: ...
    def is_ok(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def is_empty(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def __eq__(self, o: Any) -> "LazyField[bool]": ...  # type: ignore[override]
    def __ne__(self, o: Any) -> "LazyField[bool]": ...  # type: ignore[override]
    def __lt__(self, o: Any) -> "LazyField[bool]": ...
    def __le__(self, o: Any) -> "LazyField[bool]": ...
    def __gt__(self, o: Any) -> "LazyField[bool]": ...
    def __ge__(self, o: Any) -> "LazyField[bool]": ...
    def __and__(self, o: Any) -> "LazyField[bool]": ...
    def __or__(self, o: Any) -> "LazyField[bool]": ...
    def __invert__(self) -> "LazyField[bool]": ...

class LazyReference(Lazy["Reference"], Protocol):
    def join(self, href: str) -> "LazyReference": ...
    def replace(self, **fields: Any) -> "LazyReference": ...
    def resolve(self, *, browser: bool = ..., session: Any = ..., optional: bool = ..., error: _E = ..., **options: Any) -> "LazyDocument": ...
    def with_params(self, **params: str) -> "LazyReference": ...

class LazyDocument(Lazy["Document"], Protocol):
    @overload
    def attr(self, name: _LINK, *, error: _E = ...) -> "LazyReference": ...  # type: ignore[overload-overlap]
    @overload
    def attr(self, name: str, *, error: _E = ...) -> "LazyField[str]": ...
    def check(self, selector: str, checked: bool = ..., *, error: _E = ..., **kw: Any) -> "LazyDocument": ...
    def click(self, selector: str | None = ..., *, error: _E = ..., **kw: Any) -> "LazyDocument": ...
    def document(self, name: str, *, error: _E = ...) -> "LazyDocument": ...
    def documents(self, *names: str, error: _E = ...) -> "LazyCollection": ...
    def drag(self, source: str, target: str, *, error: _E = ...) -> "LazyDocument": ...
    def evaluate(self, script: str, *, error: _E = ...) -> Any: ...
    def events_of(self, event: Any) -> Any: ...
    def execute(self, script: str, *, error: _E = ...) -> "LazyDocument": ...
    def extract(self, *, error: _E = ..., **named_expr: Any) -> "LazyDocument": ...
    def field(self, name: str, *, error: _E = ...) -> "LazyField[Any]": ...
    def hover(self, selector: str, *, error: _E = ..., **kw: Any) -> "LazyDocument": ...
    def is_empty(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def is_ok(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def join(self, href: str) -> "LazyReference": ...
    def press(self, key: str, *, error: _E = ..., **kw: Any) -> "LazyDocument": ...
    def project(self, model: Any = ..., *, error: _E = ...) -> Any: ...
    def ref(self) -> "LazyReference": ...
    def reference(self, name: str, *, error: _E = ...) -> "LazyReference": ...
    def references(self, *names: str, error: _E = ...) -> "LazyCollection": ...
    def reload(self, **options: Any) -> "LazyDocument": ...
    def render(self, format: str, **options: Any) -> Any: ...
    def screenshot(self, selector: str | None = ..., *, error: _E = ..., **kw: Any) -> "LazyDocument": ...
    def scroll(self, selector: str | None = ..., *, x: int = ..., y: int = ..., error: _E = ...) -> "LazyDocument": ...
    def select(self, selector: str, *, index: int = ..., wait: float | None = ..., error: _E = ..., optional: bool = ...) -> "LazyDocument": ...
    def select_all(self, selector: str, limit: int | None = ..., offset: int = ..., *, error: _E = ...) -> "LazyCollection": ...
    def select_option(self, selector: str, *, error: _E = ..., **kw: Any) -> "LazyDocument": ...
    def subscribe(self, topic: Any, handler: Any) -> Any: ...
    def upload(self, selector: str, files: Sequence[str], *, error: _E = ...) -> "LazyDocument": ...
    def wait_for(self, selector: str | None = ..., *, error: _E = ..., **kw: Any) -> "LazyDocument": ...
    def write(self, selector: str, text: str, *, error: _E = ..., **kw: Any) -> "LazyDocument": ...

class LazyCollection(Lazy["Collection[Any]"], Protocol):
    def select(self, selector: str, *, index: int = ..., wait: float | None = ..., error: _E = ..., optional: bool = ...) -> "LazyCollection": ...
    def select_all(self, selector: str, limit: int | None = ..., offset: int = ..., *, error: _E = ...) -> "LazyCollection": ...
    def extract(self, *, error: _E = ..., **named_expr: Any) -> "LazyCollection": ...
    def filter(self, *exprs: Any, error: _E = ..., **named_expr: Any) -> "LazyCollection": ...
    def references(self, *names: str, error: _E = ...) -> "LazyCollection": ...
    def documents(self, *names: str, error: _E = ...) -> "LazyCollection": ...
    def attr(self, name: str, *, error: _E = ...) -> "LazyCollection": ...
    def is_ok(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def is_empty(self, *, error: _E = ...) -> "LazyField[bool]": ...
    def project(self, model: Any = ..., *, error: _E = ...) -> Any: ...

# <<< generated


__all__ = ["Lazy", "LazyDocument", "LazyReference", "LazyCollection", "LazyField"]
