"""Generate the registry-driven reference docs (roadmap D3: registries are the source of
truth; docs are rendered from them, never hand-maintained).

    env/bin/python scripts/gen_docs.py errors            # -> docs/errors.md
    env/bin/python scripts/gen_docs.py all               # every generator
    env/bin/python scripts/gen_docs.py all --check       # fail if any doc is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

DOCS = ROOT / "docs"


def errors_md() -> str:
    from webclient.kernel.errors import CATALOG, REMEDIES

    out = [
        "# Error catalogue",
        "",
        "*Generated by `scripts/gen_docs.py errors` from `webclient.errors.CATALOG` -- do not edit.*",
        "",
        "Every `WebError` carries a catalogued `code`, a `title`, the `message` (RFC 9457 `detail`),",
        "`status_code`, `retriable`, a `remedy` from the closed vocabulary below, a one-sentence `hint`,",
        "and is bound to the `op` / `subject` it occurred on. `WebError.problem()` renders the RFC 9457",
        "*Problem Details* form (`application/problem+json`); the HTTP service's `{\"error\": {...}}` body",
        "is the same wire shape. `type` is the legacy short kind kept stable for callers that branch on it.",
        "",
        "## Remedies",
        "",
        "| remedy | meaning |",
        "|---|---|",
    ]
    meaning = {
        "retry": "the same request may succeed later (transport blip / 429 / 5xx)",
        "browser": "re-resolve with `browser=\"always\"` (JS-gated content)",
        "proxy": "re-resolve through a fresh proxy exit (a bare block)",
        "stealth": "re-resolve in a stealth / fingerprinted browser (a named anti-bot vendor)",
        "credentials": "a login wall -- supply a session with credentials",
        "fix_selector": "the selector / attribute / path does not match -- re-read the skeleton",
        "fix_plan": "the plan / request is malformed -- correct it before re-running",
        "reproduce": "a server-side handle is gone -- re-run the plan that produced it",
        "reduce_load": "a resource cap is hit -- close / free something or wait",
        "unsupported": "the op is not available on this object -- pick another op",
        "none": "nothing to do: the target is unavailable or refused by policy",
    }
    out += [f"| `{r}` | {meaning[r]} |" for r in REMEDIES]
    out += ["", "## Codes", ""]
    groups: dict[str, list[str]] = {}
    for code in CATALOG:
        groups.setdefault(code.split(".")[0], []).append(code)
    for group, codes in groups.items():
        out += [f"### `{group}.*`", ""]
        for code in codes:
            s = CATALOG[code]
            flags = []
            if s.retriable:
                flags.append("retriable")
            if s.status_code:
                flags.append(f"status {s.status_code}")
            out += [
                f"#### `{code}` -- {s.title}",
                "",
                f"- **type** `{s.type}` · **remedy** `{s.remedy}`" + (f" · {' · '.join(flags)}" if flags else ""),
                f"- **hint**: {s.hint}",
            ]
            if s.doc:
                out.append(f"- {s.doc}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def signals_md() -> str:
    import webclient.signals.dom  # noqa: F401  (registers the rendered/tree detectors)
    from webclient.signals.registry import DETECTORS, FLAGS
    from webclient.settings import Settings

    threshold = Settings().detection.present_threshold
    out = [
        "# Signals & flags catalogue",
        "",
        "*Generated by `scripts/gen_docs.py signals` from `webclient.signals` (`DETECTORS` / `FLAGS`) -- do not edit.*",
        "",
        "A **signal** is one piece of evidence a detector reads from the response `Context` at a **stage**",
        "(`request` / `static` need only the response; `rendered` / `network` need the browser observer",
        "scripts named under *needs*). A **flag** is the conclusion: its positive signals combine by",
        f"noisy-OR, contra signals scale it down, and it is *present* at confidence >= {threshold}",
        "(`Settings.detection.present_threshold`). A present flag may carry a `remedy` (the transport",
        "escalation it calls for) and a `value` (the actionable payload).",
        "",
        f"{len(FLAGS)} flags, {len(DETECTORS)} detectors.",
        "",
    ]
    by_flag: dict[str, list] = {}
    for d in DETECTORS:
        by_flag.setdefault(d.flag, []).append(d)
    for name, spec in FLAGS.items():
        remedy = spec.remedy if isinstance(spec.remedy, str) else ("dynamic" if spec.remedy else "none")
        value_doc = (spec.value.__doc__ or "").strip().split("\n")[0] if spec.value else "none"
        out += [f"## `{name}`", "", f"- **remedy**: `{remedy}` · **value**: {value_doc}", "",
                "| detector | stage | contra | needs | evidence |", "|---|---|---|---|---|"]
        for d in by_flag.get(name, []):
            doc = (d.fn.__doc__ or "").strip().replace("\n", " ")
            doc = " ".join(doc.split())
            out.append(f"| `{d.name}` | {d.stage} | {'yes' if d.contra else ''} | {', '.join(f'`{n}`' for n in d.needs) or '—'} | {doc} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def tools_md() -> str:
    from webclient.tools import TOOLS

    out = [
        "# Tools",
        "",
        "*Generated by `scripts/gen_docs.py tools` from `webclient.tools.TOOLS` -- do not edit.*",
        "",
        "The registry every transport is generated from: Python (`webclient.tools.dispatch`,",
        "the verbs in `webclient.llm.tools`), MCP (`webclient.llm.mcp.build_tools`) and HTTP",
        "(`POST /tools/{name}`, schemas at `GET /tools`; legacy alias paths listed per tool).",
        "Arguments are validated by each tool's pydantic input model; a mismatch is a",
        "`request.invalid` error. See `docs/user-stories.md` for the stories.",
        "",
        f"{len(TOOLS)} tools.",
        "",
    ]
    for t in TOOLS.values():
        s = t.schema()
        out += [f"## `{t.name}`", "", t.description, "",
                f"- **returns**: {t.returns or '—'} · **story**: {t.story or '—'}"
                + (f" · **aliases**: {', '.join('`POST /' + a + '`' for a in t.aliases)}" if t.aliases else ""),
                "", "| argument | type | default | description |", "|---|---|---|---|"]
        required = set(s.get("required", []))
        for name, prop in s.get("properties", {}).items():
            typ = prop.get("type") or ("/".join(str(x.get("type", "?")) for x in prop.get("anyOf", [])) if "anyOf" in prop else "any")
            default = "required" if name in required else repr(prop.get("default"))
            out.append(f"| `{name}` | {typ} | {default} | {prop.get('description', '')} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


GENERATORS = {
    "errors": ("errors.md", errors_md), "signals": ("signals.md", signals_md), "tools": ("tools.md", tools_md),
}


def main(argv: list[str]) -> int:
    check = "--check" in argv
    names = [a for a in argv if not a.startswith("--")] or ["all"]
    if names == ["all"]:
        names = list(GENERATORS)
    stale = []
    for name in names:
        filename, gen = GENERATORS[name]
        target = DOCS / filename
        text = gen()
        if check:
            if not target.exists() or target.read_text() != text:
                stale.append(filename)
        else:
            target.write_text(text)
            print(f"wrote {target.relative_to(ROOT)}")
    if stale:
        print("stale docs (re-run scripts/gen_docs.py):", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
