"""Regenerate the static type surfaces that mirror runtime behaviour.

Static checkers read source, so two pieces of runtime machinery must be
spelled out for them -- and derived from the model ops so they cannot drift:

1. ``class Collection[T]`` (base.py): the element-op lifting -- every public
   op Collection does not own is re-typed to return ``Collection[<ret>]``.
2. ``webclient/lazy/stubs.py``: the two-tier *lazy* Protocols. Every surface
   op returns another lazy type; ``collect()`` (on the ``Lazy[T]`` base)
   returns the *materialised* model. At runtime one generic ``Expr`` stands in
   for all of them; these Protocols exist only for the checker.

Both are rewritten between ``>>> generated`` / ``<<< generated`` markers.

    python scripts/gen_stubs.py          # rewrite
    python scripts/gen_stubs.py --check  # exit 1 if stale (CI / test)
"""
from __future__ import annotations

import inspect
import sys
import typing
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import webclient.core.base as m  # noqa: E402
import webclient.core.document as d  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MODELS = Path(m.__file__)                         # Collection lives in base.py
STUBS = ROOT / "webclient" / "stubs.py"  # the lazy Protocols
START = "        # >>> generated by scripts/gen_stubs.py -- do not edit\n"
END = "        # <<< generated\n"
IND = "        "
SOURCES = (d.Document, d.Reference, m.WebBase)


# ========================================================================= #
# 1. Collection[T] element-op overloads (base.py)
# ========================================================================= #

def _lift(ret: str) -> str:
    ret = ret.strip().strip('"\'')
    if ret in ("Self", "T"):
        return "Collection[T]"
    if ret.startswith("Collection["):
        return ret
    return f"Collection[{ret}]"


def _render_sig(name: str, sig: inspect.Signature, ret: str) -> str:
    parts = []
    star = False
    for p in sig.parameters.values():
        if p.name == "self":
            parts.append("self")
            continue
        if p.kind is p.KEYWORD_ONLY and not star:
            parts.append("*")
            star = True
        t = p.name
        if p.kind is p.VAR_POSITIONAL:
            t, star = "*" + t, True
        elif p.kind is p.VAR_KEYWORD:
            t = "**" + t
        if p.annotation is not p.empty:
            ann = p.annotation if isinstance(p.annotation, str) else \
                getattr(p.annotation, "__name__", str(p.annotation))
            t += f": {ann}"
        if p.default is not p.empty:
            t += f" = {p.default!r}"
        parts.append(t)
    return f"{IND}def {name}({', '.join(parts)}) -> {_lift(ret)}: ...  # type: ignore[empty-body]"


def _element_ops() -> list[str]:
    own = set(vars(m.Collection))
    seen: dict[str, typing.Any] = {}
    for cls in SOURCES:
        for name, member in vars(cls).items():
            if name.startswith("_") or name in own or name in seen:
                continue
            if not getattr(member, "__webclient_op__", False):
                continue
            seen[name] = member
    lines: list[str] = []
    for name in sorted(seen):
        member = seen[name]
        if name == "attr":                       # the one overloaded op
            lines += [
                f"{IND}@overload  # type: ignore[overload-overlap]",
                f"{IND}def attr(self, name: Literal['href', 'src', 'action'], *, "
                "error: ErrorPolicy | None = None) -> Collection[Reference]: ...",
                f"{IND}@overload",
                f"{IND}def attr(self, name: str, *, error: ErrorPolicy | None = None) "
                "-> Collection[Field[str]]: ...",
                f"{IND}def attr(self, name: str, *, error: ErrorPolicy | None = None) "
                "-> Any: ...  # type: ignore[empty-body]",
            ]
            continue
        try:
            hints = typing.get_type_hints(member)
        except Exception:
            hints = {}
        ret = hints.get("return")
        ret_name = ("Collection[Reference]" if name == "references"
                    else "Collection[Document]" if name == "documents"
                    else _ann(ret))
        lines.append(_render_sig(name, inspect.signature(member), ret_name))
    return lines


def _ann(ret: typing.Any) -> str:
    if ret is None:
        return "Any"
    return getattr(ret, "__name__", None) or str(ret).replace("typing.", "")


def collection_block() -> str:
    return "".join([START, *(ln + "\n" for ln in _element_ops()), END])


# ========================================================================= #
# 2. Lazy Protocol tiers (lazy/stubs.py)
# ========================================================================= #

LSTART = "# >>> generated by scripts/gen_stubs.py -- do not edit\n"
LEND = "# <<< generated\n"


def _raw_ret(member: typing.Any) -> str:
    """The op's *declared* (string) return annotation -- ``from __future__
    import annotations`` keeps these as source strings, which is exactly the
    shape the lazy-return mapping wants."""
    return str(getattr(member, "__annotations__", {}).get("return", "Any"))


def _lazy_ret(ret: str, selfty: str) -> str:
    """Map a materialised return type onto its lazy tier."""
    r = ret.strip().strip('"\'')
    if r == "Self":
        return selfty
    if r.startswith("Collection"):
        return '"LazyCollection"'
    if r == "Document":
        return '"LazyDocument"'
    if r == "Reference":
        return '"LazyReference"'
    if r.startswith("Field"):
        inner = r[len("Field"):].strip()
        inner = inner[1:-1] if inner.startswith("[") else ""
        return f'"LazyField[{inner or "Any"}]"'
    return "Any"                                   # render/evaluate/scalars


_SAFE = {"str", "int", "bool", "float", "Any", "None",
         "str | None", "int | None", "bool | None", "float | None",
         "Sequence[str]"}


def _pann(p: inspect.Parameter) -> str:
    """A checker-safe annotation for one lazy-surface parameter: ``error`` is
    the opaque policy arg; otherwise keep import-safe primitives, else ``Any``
    (parameter types are incidental to the two-tier return surface)."""
    if p.name == "error":
        return "_E"
    if p.annotation is p.empty:
        return "Any"
    ann = p.annotation if isinstance(p.annotation, str) else \
        getattr(p.annotation, "__name__", str(p.annotation))
    return ann if ann in _SAFE else "Any"


def _lazy_params(member: typing.Any) -> str:
    parts: list[str] = []
    star = False
    for p in inspect.signature(member).parameters.values():
        if p.name == "self":
            continue
        if p.kind is p.VAR_POSITIONAL:
            parts.append(f"*{p.name}: {_pann(p)}")
            star = True
            continue
        if p.kind is p.VAR_KEYWORD:
            parts.append(f"**{p.name}: {_pann(p)}")
            continue
        if p.kind is p.KEYWORD_ONLY and not star:
            parts.append("*")
            star = True
        t = f"{p.name}: {_pann(p)}"
        if p.default is not p.empty:
            t += " = ..."
        parts.append(t)
    return ", ".join(parts)


def _method(name: str, member: typing.Any, selfty: str,
            forced: str | None = None) -> list[str]:
    """One lazy method line, deriving its signature from the real op and its
    return from the lazy-tier mapping (``forced`` overrides the mapping)."""
    ret = forced or _lazy_ret(_raw_ret(member), selfty)
    params = _lazy_params(member)
    sig = "self" + (f", {params}" if params else "")
    return [f"    def {name}({sig}) -> {ret}: ..."]


def _policy_ops(*classes: type) -> dict[str, typing.Any]:
    out: dict[str, typing.Any] = {}
    for cls in classes:
        for name, member in vars(cls).items():
            if name.startswith("_") or name in out:
                continue
            if getattr(member, "__webclient_op__", False):
                out[name] = member
    return out


def _attr_overloads(link: str, field: str) -> list[str]:
    # the link-likes narrow to a Reference; the intentional str-overlap is
    # silenced on the first def (where both checkers anchor the diagnostic).
    return [
        '    @overload',
        f'    def attr(self, name: _LINK, *, error: _E = ...) -> {link}: ...  # type: ignore[overload-overlap]',
        '    @overload',
        f'    def attr(self, name: str, *, error: _E = ...) -> {field}: ...',
    ]


def _lazy_field() -> list[str]:
    """The scalar leaf: operator- and ``when``-heavy, so spelled out. ``get``
    returns the element type; comparisons and branching stay in the lazy tier."""
    ops = ["eq", "ne", "lt", "le", "gt", "ge", "and", "or"]
    dunder = {"eq": "__eq__", "ne": "__ne__", "lt": "__lt__", "le": "__le__",
              "gt": "__gt__", "ge": "__ge__", "and": "__and__", "or": "__or__"}
    lines = [
        'class LazyField[T](Lazy["Field[T]"], Protocol):',
        '    """A lazy scalar; ``collect()`` -> ``Field[T]`` (then ``.get()`` -> T)."""',
        '    def get(self) -> T: ...',
        '    def is_ok(self, *, error: _E = ...) -> "LazyField[bool]": ...',
        '    def is_empty(self, *, error: _E = ...) -> "LazyField[bool]": ...',
        '    def when(self, cond: "LazyField[bool] | bool") -> "LazyField[T]": ...',
        '    def then(self, value: Any) -> "LazyField[T]": ...',
        '    def otherwise(self, value: Any) -> "LazyField[T]": ...',
    ]
    for op in ops:
        ignore = "  # type: ignore[override]" if op in ("eq", "ne") else ""
        lines.append(f'    def {dunder[op]}(self, o: Any) -> "LazyField[bool]": ...{ignore}')
    lines.append('    def __invert__(self) -> "LazyField[bool]": ...')
    return lines


def _lazy_reference() -> list[str]:
    lines = ['class LazyReference(Lazy["Reference"], Protocol):']
    for name, member in sorted(_policy_ops(d.Reference).items()):
        lines += _method(name, member, '"LazyReference"')
    # non-policy but recordable transforms (pure reference derivations)
    for name in ("with_params", "replace", "join"):
        lines += _method(name, getattr(d.Reference, name), '"LazyReference"',
                         forced='"LazyReference"')
    return lines


def _lazy_document() -> list[str]:
    ops = _policy_ops(d.Document, m.WebBase)
    lines = ['class LazyDocument(Lazy["Document"], Protocol):']
    for name in sorted(ops):
        if name == "attr":
            lines += _attr_overloads('"LazyReference"', '"LazyField[str]"')
            continue
        lines += _method(name, ops[name], '"LazyDocument"')
    # project is terminal (not a @policy op) -> an opaque value
    lines.append('    def project(self, model: Any = ..., *, error: _E = ...) -> Any: ...')
    return lines


def _lazy_collection() -> list[str]:
    """Element ops map over the collection -> another ``LazyCollection``;
    whole-collection predicates collapse to a scalar; ``project`` is opaque."""
    lines = ['class LazyCollection(Lazy["Collection[Any]"], Protocol):']
    spec = [("select", d.Document.select), ("select_all", d.Document.select_all),
            ("extract", m.WebBase.extract), ("filter", m.Collection.filter),
            ("references", m.WebBase.references), ("documents", m.WebBase.documents)]
    for name, member in spec:
        lines += _method(name, member, '"LazyCollection"', forced='"LazyCollection"')
    lines.append('    def attr(self, name: str, *, error: _E = ...) -> "LazyCollection": ...')
    for name in ("is_ok", "is_empty"):
        lines += _method(name, getattr(m.WebBase, name), '', forced='"LazyField[bool]"')
    lines.append('    def project(self, model: Any = ..., *, error: _E = ...) -> Any: ...')
    return lines


def lazy_block() -> str:
    body: list[str] = []
    for chunk in (_lazy_field(), _lazy_reference(), _lazy_document(),
                  _lazy_collection()):
        body += chunk
        body.append("")                            # blank line between classes
    return "".join([LSTART, *(ln + "\n" for ln in body), LEND])


# ========================================================================= #
# Driver
# ========================================================================= #

def _rewrite(path: Path, start: str, end: str, block: str, check: bool) -> int:
    text = path.read_text()
    i, j = text.index(start), text.index(end) + len(end)
    new = text[:i] + block + text[j:]
    if new == text:
        return 0
    if check:
        print(f"{path.name} generated block is stale: run scripts/gen_stubs.py")
        return 1
    path.write_text(new)
    print(f"{path.name} generated block regenerated")
    return 0


def main(check: bool) -> int:
    rc = _rewrite(MODELS, START, END, collection_block(), check)
    rc |= _rewrite(STUBS, LSTART, LEND, lazy_block(), check)
    return rc


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv))
