"""Generate the registry-driven reference docs (roadmap D3: registries are the source of
truth; docs are rendered from them, never hand-maintained).

    env/bin/python scripts/gen_docs.py errors            # -> docs/errors.md
    env/bin/python scripts/gen_docs.py all               # every generator
    env/bin/python scripts/gen_docs.py all --check       # fail if any doc is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

DOCS = ROOT / "docs"


def errors_md() -> str:
    from webclient.errors import CATALOG, REMEDIES

    out = [
        "# Error catalogue",
        "",
        "*Generated by `scripts/gen_docs.py errors` from `webclient.errors.CATALOG` -- do not edit.*",
        "",
        "Every `WebError` carries a catalogued `code`, a `title`, the `message` (RFC 9457 `detail`),",
        "`status_code`, `retriable`, a `remedy` from the closed vocabulary below, a one-sentence `hint`,",
        "and is bound to the `op` / `subject` it occurred on. `WebError.problem()` renders the RFC 9457",
        "*Problem Details* form (`application/problem+json`); the HTTP service's `{\"error\": {...}}` body",
        "is the same wire shape. `type` is the legacy short kind kept stable for callers that branch on it.",
        "",
        "## Remedies",
        "",
        "| remedy | meaning |",
        "|---|---|",
    ]
    meaning = {
        "retry": "the same request may succeed later (transport blip / 429 / 5xx)",
        "browser": "re-resolve with `browser=\"always\"` (JS-gated content)",
        "proxy": "re-resolve through a fresh proxy exit (a bare block)",
        "stealth": "re-resolve in a stealth / fingerprinted browser (a named anti-bot vendor)",
        "credentials": "a login wall -- supply a session with credentials",
        "fix_selector": "the selector / attribute / path does not match -- re-read the skeleton",
        "fix_plan": "the plan / request is malformed -- correct it before re-running",
        "reproduce": "a server-side handle is gone -- re-run the plan that produced it",
        "reduce_load": "a resource cap is hit -- close / free something or wait",
        "unsupported": "the op is not available on this object -- pick another op",
        "none": "nothing to do: the target is unavailable or refused by policy",
    }
    out += [f"| `{r}` | {meaning[r]} |" for r in REMEDIES]
    out += ["", "## Codes", ""]
    groups: dict[str, list[str]] = {}
    for code in CATALOG:
        groups.setdefault(code.split(".")[0], []).append(code)
    for group, codes in groups.items():
        out += [f"### `{group}.*`", ""]
        for code in codes:
            s = CATALOG[code]
            flags = []
            if s.retriable:
                flags.append("retriable")
            if s.status_code:
                flags.append(f"status {s.status_code}")
            out += [
                f"#### `{code}` -- {s.title}",
                "",
                f"- **type** `{s.type}` · **remedy** `{s.remedy}`" + (f" · {' · '.join(flags)}" if flags else ""),
                f"- **hint**: {s.hint}",
            ]
            if s.doc:
                out.append(f"- {s.doc}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


GENERATORS = {"errors": ("errors.md", errors_md)}


def main(argv: list[str]) -> int:
    check = "--check" in argv
    names = [a for a in argv if not a.startswith("--")] or ["all"]
    if names == ["all"]:
        names = list(GENERATORS)
    stale = []
    for name in names:
        filename, gen = GENERATORS[name]
        target = DOCS / filename
        text = gen()
        if check:
            if not target.exists() or target.read_text() != text:
                stale.append(filename)
        else:
            target.write_text(text)
            print(f"wrote {target.relative_to(ROOT)}")
    if stale:
        print("stale docs (re-run scripts/gen_docs.py):", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
