"""Regenerate the ``Collection[T]`` element-op overloads in ``models.py``.

Static checkers read source, so the lifting the Collection does at runtime
(``many.select(...)`` maps ``Document.select`` over the elements) must be
spelled out for them. This derives it from the surface classes: every public
method on Document / Reference / WebBase that Collection does not own itself,
re-typed to return ``Collection[<its return>]``, written between the markers
in ``class Collection`` under ``if TYPE_CHECKING:``.

    python scripts/gen_stubs.py          # rewrite
    python scripts/gen_stubs.py --check  # exit 1 if stale (CI / test)
"""
from __future__ import annotations

import inspect
import sys
import typing
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import webclient.core.base as m  # noqa: E402
import webclient.document as d  # noqa: E402

MODELS = Path(m.__file__)   # Collection (with the markers) lives in base.py
START = "        # >>> generated by scripts/gen_stubs.py -- do not edit\n"
END = "        # <<< generated\n"
IND = "        "
SOURCES = (d.Document, d.Reference, m.WebBase)


def _lift(ret: str) -> str:
    ret = ret.strip().strip('"\'')
    if ret in ("Self", "T"):
        return "Collection[T]"
    if ret.startswith("Collection["):
        return ret
    return f"Collection[{ret}]"


def _render_sig(name: str, sig: inspect.Signature, ret: str) -> str:
    parts = []
    star = False
    for p in sig.parameters.values():
        if p.name == "self":
            parts.append("self")
            continue
        if p.kind is p.KEYWORD_ONLY and not star:
            parts.append("*")
            star = True
        t = p.name
        if p.kind is p.VAR_POSITIONAL:
            t, star = "*" + t, True
        elif p.kind is p.VAR_KEYWORD:
            t = "**" + t
        if p.annotation is not p.empty:
            ann = p.annotation if isinstance(p.annotation, str) else \
                getattr(p.annotation, "__name__", str(p.annotation))
            t += f": {ann}"
        if p.default is not p.empty:
            t += f" = {p.default!r}"
        parts.append(t)
    return f"{IND}def {name}({', '.join(parts)}) -> {_lift(ret)}: ...  # type: ignore[empty-body]"


def _element_ops() -> list[str]:
    own = set(vars(m.Collection))
    seen: dict[str, Any] = {}
    for cls in SOURCES:
        for name, member in vars(cls).items():
            if name.startswith("_") or name in own or name in seen:
                continue
            if not getattr(member, "__webclient_op__", False):
                continue
            seen[name] = member
    lines: list[str] = []
    for name in sorted(seen):
        member = seen[name]
        if name == "attr":                       # the one overloaded op
            lines += [
                f"{IND}@overload  # type: ignore[overload-overlap]",
                f"{IND}def attr(self, name: Literal['href', 'src', 'action'], *, "
                "error: ErrorPolicy | None = None) -> Collection[Reference]: ...",
                f"{IND}@overload",
                f"{IND}def attr(self, name: str, *, error: ErrorPolicy | None = None) "
                "-> Collection[Field[str]]: ...",
                f"{IND}def attr(self, name: str, *, error: ErrorPolicy | None = None) "
                "-> Any: ...  # type: ignore[empty-body]",
            ]
            continue
        try:
            hints = typing.get_type_hints(member)
        except Exception:
            hints = {}
        ret = hints.get("return")
        ret_name = ("Collection[Reference]" if name == "references"
                    else "Collection[Document]" if name == "documents"
                    else _ann(ret))
        lines.append(_render_sig(name, inspect.signature(member), ret_name))
    return lines


def _ann(ret: Any) -> str:
    if ret is None:
        return "Any"
    return getattr(ret, "__name__", None) or str(ret).replace("typing.", "")


def block() -> str:
    body = [START]
    body += [ln + "\n" for ln in _element_ops()]
    body.append(END)
    return "".join(body)


def main(check: bool) -> int:
    text = MODELS.read_text()
    i, j = text.index(START), text.index(END) + len(END)
    new = text[:i] + block() + text[j:]
    if new == text:
        return 0
    if check:
        print("models.py Collection stub is stale: run scripts/gen_stubs.py")
        return 1
    MODELS.write_text(new)
    print("models.py Collection stub regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv))
