"""Company onboarding -- the pipeline as a package.

The pipeline is a package: one module per stage (search / crawl / select / evaluate /
reference / query / review) plus the artifacts, the LLM plumbing and the orchestrator;
every name (public and private) is re-exported here so ``webclient.pipelines.onboarding``
stays one import surface.
"""

from __future__ import annotations

from .common import (  # noqa: F401
    LLM,
    SearchFn,
    BrowserMode,
    _mode,
    _FULL_SKELETON,
    _MAX_SKELETON_CHARS,
    _MAX_LISTING_CHARS,
    _MAX_PAGES_CHARS,
    _skeleton_for,
    _clip,
    log,
)
from .artifacts import (  # noqa: F401
    _parse_frontmatter,
    _strip_optional,
    _parse_schema,
    SchemaField,
    Brief,
    SearchHit,
    Seed,
    Candidate,
    CandidateEval,
    QueryPart,
    QueryArtifact,
    Review,
    OnboardingResult,
    _RunArtifacts,
    _NOISY_LOGGERS,
    _ensure_logging,
    _trace,
    _cell,
    _render_table,
    _resolve_summary,
    _summarize,
)
from .llm import (  # noqa: F401
    _strip_fences,
    _json_blob,
    _ask_json,
    _schema_outline,
    _fields_line,
    _DECISION_FLAGS,
    _read_flags,
)
from .search import (  # noqa: F401
    ddg_search,
    _apply_search_term,
    _search_query,
    _seeds_for_company,
    search_web,
)
from .crawl import (  # noqa: F401
    _frontier_key,
    _PAGE_PARAMS,
    _DOCS_HINTS,
    _is_docs_url,
    _DATA_DOC_HINTS,
    _is_data_doc,
    _reg_domain,
    _seed_domains,
    _filter_frontier,
    _pick_edges,
    crawl_from_seeds,
    _log_crawl_progress,
)
from .select import (  # noqa: F401
    select_candidates,
)
from .evaluate import (  # noqa: F401
    evaluate_candidate,
    evaluate_candidates,
    _candidate_score,
)
from .reference import (  # noqa: F401
    _source_url,
    write_reference,
    write_resolve,
)
from .query import (  # noqa: F401
    _query_prompt,
    _recency_guidance,
    _data_rows,
    _extraction_steps,
    _paginate_steps,
    _executable_query,
    _reroot,
    _query_code,
    _QUERY_CONST,
    _eval_query_ast,
    _parse_query,
    _QUERY_SPLIT,
    _split_queries,
    _parse_queries,
    _row_selector,
    _selector_match_count,
    _no_rows_hint,
    _sample_record_html,
    _nonempty,
    _populated_rows,
    _required_leaf_paths,
    _empty_required_fields,
    _content_hint,
    _QUERY_TEST_TIMEOUT,
    _test_query,
    run_query,
    _SEL_CLASS,
    _record_classes,
    _selector_hits,
    _repair_selector,
    _iter_field_select_args,
    _iter_all_select_args,
    _CHILD_COMBINATOR,
    _normalize_selectors,
    _repair_query,
    _short_fail_reason,
    _artifact_from,
    _representative_sample,
    _combined_artifact,
    AuthoringError,
    Author,
    _TextAuthor,
    _query_loop_prompt,
    _llm_query_policy,
    _LoopAuthor,
    _make_author,
    _resolve_on_non_link,
    _should_retry_for_recency,
    _precheck_sections,
    _split_section_follow_up,
    _recency_follow_up,
    write_query,
)
from .dates import (  # noqa: F401
    _TIMELINESS_INTERVALS,
    _CHECK_COMPLETENESS,
    _COMPLETENESS_BLOCK,
    _COMPLETENESS_OFF,
    _parse_date,
    _DATE_LEAVES,
    _date_field_paths,
    _dig,
    _timeliness,
)
from .review import (  # noqa: F401
    _as_bool,
    _review_from_json,
    _page_lines,
    review_crawl,
    review_select,
    review_query,
    review_query_exit,
    review_failure,
    _note_review,
    diagnose_failure,
)
from .orchestrate import (  # noqa: F401
    onboard_company,
    _build_pipeline,
    _Ctx,
    onboard,
)

__all__ = [
    "LLM",
    "SearchFn",
    "BrowserMode",
    "log",
    "SchemaField",
    "Brief",
    "SearchHit",
    "Seed",
    "Candidate",
    "CandidateEval",
    "QueryPart",
    "QueryArtifact",
    "Review",
    "OnboardingResult",
    "ddg_search",
    "search_web",
    "crawl_from_seeds",
    "select_candidates",
    "evaluate_candidate",
    "evaluate_candidates",
    "write_reference",
    "write_resolve",
    "run_query",
    "AuthoringError",
    "Author",
    "write_query",
    "review_crawl",
    "review_select",
    "review_query",
    "review_query_exit",
    "review_failure",
    "diagnose_failure",
    "onboard_company",
    "onboard",
]
