"""P0/P2 typing gate: authoring plans must type-check under mypy --strict and
pyright. The lazy roots are typed via ``lazy(cls) -> cls``; the Collection
element-op block is generated by scripts/gen_stubs.py."""
from typing import Any, assert_type

from webclient import (
    IGNORE,
    Collection,
    Document,
    Field,
    Reference,
    WebBase,
    doc,
    lazy,
    many,
    ref,
    reference,
    when,
)

assert_type(doc, Document)
assert_type(many, Collection[Document])
assert_type(ref, Reference)

# element ops on a Document
assert_type(doc.select("a").select_all("li"), Collection[Document])
assert_type(doc.attr("text"), Field[str])
assert_type(doc.attr("href"), Reference)                         # link attrs narrow
assert_type(doc.attr("href").resolve().attr("text"), Field[str])

# async ops present a sync return (the @policy decorator unwraps Awaitable)
assert_type(ref.resolve(), Document)
assert_type(ref.resolve(error=IGNORE), Document)

# Field comparisons / branching
title: Field[str] = Field[str]()
assert_type(title == "x", Field[bool])
assert_type((title != "x") & ~(title == "y"), Field[bool])
# branching is the free Polars-style builder (not a Field method)
assert_type(when(title == "").then("n/a").otherwise(title), Field[Any])
assert_type(title.get(), str)

# Collection lifts element ops and keeps the element type
assert_type(many.select("a"), Collection[Document])
assert_type(many.select("a").attr("href"), Collection[Reference])
assert_type(many.attr("text"), Collection[Field[str]])
assert_type(many.filter(title == "x"), Collection[Document])
assert_type(many.extract(name=title), Collection[Document])

# WebBase accessors + error= surface
base = lazy(WebBase)
assert_type(base.field("t"), Field[Any])
assert_type(base.field("t", error=IGNORE), Field[Any])
assert_type(base.reference("r"), Reference)
assert_type(base.references("a", "b"), Collection[Reference])
assert_type(base.document("d"), Document)
assert_type(base.is_ok(), Field[bool])

# reference("url") is a lazy root, typed as Reference
assert_type(reference("https://e.com"), Reference)
assert_type(reference("https://e.com").resolve().select("a").attr("text"), Field[str])

# extract -> project pipeline
assert_type(doc.select_all("li").extract(t=doc.attr("text")).project(),
            list[dict[str, Any]])

# item 3: render() is the single representation function, typed per format
from webclient import Element
res_doc = reference("https://e.com").resolve()
assert_type(res_doc.render("markdown"), str)
assert_type(res_doc.render("elements"), list[Element])
assert_type(res_doc.render("links"), Collection[Reference])

# iterating a Collection yields the element type
for _card in doc.select_all(".card"):
    assert_type(_card, Document)


# -- Two-tier lazy client surface (PLAN §8): entry points are lazy; collect()
#    returns the materialised tier. Runtime is a generic Expr; these are stubs.
from webclient import AsyncWebClient, WebClient
from webclient.interface import LazyDocument, LazyField, LazyReference

_wc = WebClient()
assert_type(_wc.ref("https://e.com"), LazyReference)
assert_type(_wc.fetch("https://e.com"), LazyDocument)
assert_type(_wc.fetch("https://e.com").select(".t"), LazyDocument)
assert_type(_wc.fetch("https://e.com").attr("href"), LazyReference)
assert_type(_wc.fetch("https://e.com").attr("text"), LazyField[str])
assert_type(_wc.fetch("https://e.com").collect(), Document)
assert_type(_wc.fetch("https://e.com").attr("text").collect(), Field[str])
assert_type(_wc.ref("https://e.com").resolve().collect(), Document)
assert_type(_wc.ref("https://e.com").resolve().select(".t").attr("text").collect(), Field[str])

# execute() materialises a lazy tier to its model via the Lazy[T] bridge
assert_type(_wc.execute(_wc.fetch("https://e.com")), Document)
assert_type(_wc.execute(_wc.ref("https://e.com")), Reference)
assert_type(_wc.execute(_wc.fetch("https://e.com").attr("text")), Field[str])

# the async client awaits to the same materialised model
_ac = AsyncWebClient()
assert_type(_ac.fetch("https://e.com"), LazyDocument)


async def _async_surface() -> None:
    # awaiting execute() materialises the lazy tier to its model
    assert_type(await _ac.execute(_ac.fetch("https://e.com")), Document)
    assert_type(await _ac.execute(_ac.ref("https://e.com").resolve()), Document)
    assert_type(await _ac.execute(_ac.fetch("https://e.com").attr("text")), Field[str])
