"""The typed surfaces.

The eager surfaces ARE the cores; sync / async / remote / lazy are just different
dispatchers on those cores, typed by generated stubs. Split into:
- :mod:`._base` -- ``wrap`` (a list of cores -> a ``Collection``).
- :mod:`.interface` -- every dispatch-view stub in one file: the eager surfaces
  (``Document`` / ``Reference`` / ``WebClient`` / ``Session``), the async / remote
  views (``Async*`` / ``Remote*``), and the lazy recorder tier (``Lazy*`` / ``wq``) --
  all WHOLE-CLASS generated by ``scripts/gen_stubs.py``.

Re-exported here so ``from webclient.surfaces import X`` reaches every surface.
"""

from ._base import wrap
from .interface import (
    AsyncDocument, AsyncReference, AsyncWebClient, Document, Lazy, LazyCollection,
    LazyDocument, LazyField, LazyReference, LazyWebClient, LiveDocument, Reference,
    RemoteDocument, RemoteReference, RemoteWebClient, Session, WebClient, WebQuery,
    default_client, doc, field, filter, from_url, is_empty, is_ok, many, ref,
    reference, when, wq,
)

__all__ = [
    "wrap",
    "Reference",
    "Document",
    "AsyncReference",
    "AsyncDocument",
    "LiveDocument",
    "Session",
    "WebClient",
    "AsyncWebClient",
    "RemoteWebClient",
    "default_client",
    "from_url",
    "Lazy",
    "LazyField",
    "LazyReference",
    "LazyDocument",
    "LazyCollection",
    "WebQuery",
    "wq",
    "doc",
    "ref",
    "many",
    "reference",
    "field",
    "when",
    "filter",
    "is_empty",
    "is_ok",
]
