"""The typed surfaces.

The eager surfaces ARE the cores (typing stubs over them, generated by
``scripts/gen_stubs.py``); sync / async / remote are just different dispatchers
on those cores. Split into:
- :mod:`._base` -- ``wrap`` (a list of cores -> a ``Collection``).
- :mod:`.eager` -- the eager surfaces (``Document`` / ``Reference`` /
  ``WebClient`` / ``AsyncWebClient`` / ``Session`` / ``RemoteWebClient`` / ...),
  runtime aliases to their cores plus typed stubs.
- :mod:`.lazy` -- the lazy recorder tier (``LazyDocument`` / ``LazyReference`` /
  ``LazyField`` / ``LazyCollection`` / ``LazyWebClient``).

Re-exported here so ``from webclient.surfaces import X`` reaches every surface.
"""

from ._base import wrap
from .eager import (
    AsyncDocument,
    AsyncReference,
    AsyncWebClient,
    Document,
    LiveDocument,
    Reference,
    RemoteWebClient,
    Renderer,
    Session,
    WebClient,
    default_client,
    from_url,
)
from .lazy import (
    Lazy,
    LazyCollection,
    LazyDocument,
    LazyField,
    LazyReference,
    WebQuery,
    doc,
    field,
    filter,
    is_empty,
    is_ok,
    many,
    ref,
    reference,
    when,
    wq,
)

__all__ = [
    "wrap",
    "Reference",
    "Document",
    "AsyncReference",
    "AsyncDocument",
    "LiveDocument",
    "Renderer",
    "Session",
    "WebClient",
    "AsyncWebClient",
    "RemoteWebClient",
    "default_client",
    "from_url",
    "Lazy",
    "LazyField",
    "LazyReference",
    "LazyDocument",
    "LazyCollection",
    "WebQuery",
    "wq",
    "doc",
    "ref",
    "many",
    "reference",
    "field",
    "when",
    "filter",
    "is_empty",
    "is_ok",
]
